export const LOGIN_USER = "LOGIN_USER";
export const GET_TOKEN = "GET_TOKEN";
export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_USER = "REGISTER_USER";

export const GET_EXPENSE_TYPES = "GET_EXPENSE_TYPES";
export const DELETE_EXPENSE_TYPE = "DELETE_EXPENSE_TYPE";
export const ADD_EXPENSE_TYPE = "ADD_EXPENSE_TYPE";

export const GET_USERS = "GET_USERS";
export const DELETE_USER = "DELETE_USER";
export const SOFT_DELETE_USER = "SOFT_DELETE_USER";
