export const LOGIN_USER = "LOGIN_USER";
export const GET_TOKEN = "GET_TOKEN";
export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_USER = "REGISTER_USER";

export const GET_EXPENSE_TYPES = "GET_EXPENSE_TYPES";
export const DELETE_EXPENSE_TYPE = "DELETE_EXPENSE_TYPE";
export const ADD_EXPENSE_TYPE = "ADD_EXPENSE_TYPE";

export const GET_USERS = "GET_USERS";
export const DELETE_USER = "DELETE_USER";
export const SOFT_DELETE_USER = "SOFT_DELETE_USER";

export const ADD_HOUSEHOLD = "ADD_HOUSEHOLD";
export const GET_HOUSHOLDS = "GET_HOUSHOLDS";
export const GET_PRIMARY_HOUSHOLDS = "GET_PRIMARY_HOUSHOLDS";
export const DELETE_HOUSHOLD = "DELETE_HOUSHOLD";

export const GET_MEMBERS = "GET_MEMBERS";
export const GET_HOUSEHOLD_MEMBERS = "GET_HOUSEHOLD_MEMBERS";
export const DELETE_MEMBER = "DELETE_MEMBER";
